[mypy]
ignore_missing_imports = True
disable_error_code = attr-defined
follow_imports = skip

[mypy-casbin.*]
ignore_errors = True

[mypy-fastapi_cache2.*]
ignore_errors = True

[mypy-fastapi_users.*]
ignore_errors = True
